package com.bytedance.sdk.openadsdk.sAl;

import android.content.Context;
import android.graphics.Color;
import android.graphics.drawable.Drawable;
import android.text.TextUtils;
import android.util.AttributeSet;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.SeekBar;
import com.bytedance.sdk.component.utils.om;
import com.bytedance.sdk.openadsdk.utils.Cox;
import com.mbridge.msdk.foundation.entity.CampaignEx;

/* JADX INFO: loaded from: classes3.dex */
public class sAl extends com.bytedance.sdk.openadsdk.core.TFq.Mm {
    public sAl(Context context) {
        this(context, null);
    }

    private void ZRu(Context context) {
        setId(520093726);
        setBackgroundColor(-1);
        com.bytedance.sdk.openadsdk.core.TFq.Mm mm = new com.bytedance.sdk.openadsdk.core.TFq.Mm(context);
        mm.setId(com.bytedance.sdk.openadsdk.utils.sAl.YuF);
        mm.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        mm.setBackgroundColor(0);
        mm.setGravity(17);
        addView(mm);
        View uRVar = new com.bytedance.sdk.openadsdk.core.TFq.uR(context);
        uRVar.setId(com.bytedance.sdk.openadsdk.utils.sAl.kkl);
        uRVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        mm.addView(uRVar);
        com.bytedance.sdk.openadsdk.core.TFq.Ht ht = new com.bytedance.sdk.openadsdk.core.TFq.Ht(context);
        ht.setId(com.bytedance.sdk.openadsdk.utils.sAl.zr);
        int iMZ = Cox.mZ(context, 60.0f);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(iMZ, iMZ);
        layoutParams.addRule(13);
        ht.setLayoutParams(layoutParams);
        ht.setIndeterminateDrawable(com.bytedance.sdk.openadsdk.utils.FA.ZRu(context, "tt_video_loading_progress_bar"));
        mm.addView(ht);
        com.bytedance.sdk.openadsdk.core.TFq.TFq tFq = new com.bytedance.sdk.openadsdk.core.TFq.TFq(context);
        tFq.setId(com.bytedance.sdk.openadsdk.utils.sAl.f140687rd);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams2.addRule(13);
        tFq.setLayoutParams(layoutParams2);
        tFq.setGravity(1);
        tFq.setOrientation(1);
        tFq.setVisibility(8);
        mm.addView(tFq);
        com.bytedance.sdk.openadsdk.core.TFq.uR uRVar2 = new com.bytedance.sdk.openadsdk.core.TFq.uR(context);
        uRVar2.setId(com.bytedance.sdk.openadsdk.utils.sAl.CA);
        uRVar2.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        uRVar2.setImageDrawable(com.bytedance.sdk.openadsdk.utils.FA.ZRu(context, "tt_refreshing_video_textpage"));
        ImageView.ScaleType scaleType = ImageView.ScaleType.CENTER;
        uRVar2.setScaleType(scaleType);
        tFq.addView(uRVar2);
        com.bytedance.sdk.openadsdk.core.TFq.FA fa2 = new com.bytedance.sdk.openadsdk.core.TFq.FA(context);
        fa2.setId(com.bytedance.sdk.openadsdk.utils.sAl.Guy);
        fa2.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        fa2.setText(om.ZRu(context, "tt_video_retry_des_txt"));
        fa2.setTextColor(Color.parseColor("#999999"));
        tFq.addView(fa2);
        com.bytedance.sdk.openadsdk.core.TFq.uR uRVar3 = new com.bytedance.sdk.openadsdk.core.TFq.uR(context);
        uRVar3.setId(com.bytedance.sdk.openadsdk.utils.sAl.eqw);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams3.addRule(13);
        uRVar3.setLayoutParams(layoutParams3);
        uRVar3.setScaleType(scaleType);
        uRVar3.setImageDrawable(com.bytedance.sdk.openadsdk.utils.FA.ZRu(context, "tt_play_movebar_textpage"));
        uRVar3.setVisibility(8);
        addView(uRVar3);
        com.bytedance.sdk.openadsdk.core.TFq.uR uRVar4 = new com.bytedance.sdk.openadsdk.core.TFq.uR(context);
        uRVar4.setId(com.bytedance.sdk.openadsdk.utils.sAl.aNu);
        int iMZ2 = Cox.mZ(context, 30.0f);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(iMZ2, iMZ2);
        layoutParams4.addRule(21);
        layoutParams4.addRule(11);
        int iMZ3 = Cox.mZ(context, 7.0f);
        layoutParams4.setMarginEnd(iMZ3);
        layoutParams4.rightMargin = iMZ3;
        layoutParams4.topMargin = iMZ3;
        uRVar4.setLayoutParams(layoutParams4);
        uRVar4.setBackground(com.bytedance.sdk.openadsdk.utils.FA.ZRu(context, "tt_detail_video_btn_bg"));
        uRVar4.setScaleType(scaleType);
        uRVar4.setImageDrawable(com.bytedance.sdk.openadsdk.utils.FA.ZRu(context, "tt_close_move_detail"));
        addView(uRVar4);
        com.bytedance.sdk.openadsdk.core.TFq.FA fa3 = new com.bytedance.sdk.openadsdk.core.TFq.FA(context);
        fa3.setId(com.bytedance.sdk.openadsdk.utils.sAl.IJM);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(9);
        layoutParams5.addRule(20);
        layoutParams5.addRule(10);
        fa3.setLayoutParams(layoutParams5);
        fa3.setBackground(com.bytedance.sdk.openadsdk.utils.FA.ZRu(context, "tt_video_black_desc_gradient"));
        TextUtils.TruncateAt truncateAt = TextUtils.TruncateAt.END;
        fa3.setEllipsize(truncateAt);
        fa3.setMaxLines(2);
        int iMZ4 = Cox.mZ(context, 15.0f);
        fa3.setPadding(iMZ4, Cox.mZ(context, 14.0f), iMZ4, 0);
        fa3.setSingleLine(false);
        fa3.setTextColor(-1);
        fa3.setTextSize(2, 17.0f);
        fa3.setVisibility(8);
        addView(fa3);
        com.bytedance.sdk.openadsdk.core.TFq.Mm mm2 = new com.bytedance.sdk.openadsdk.core.TFq.Mm(context);
        mm2.setId(com.bytedance.sdk.openadsdk.utils.sAl.f140686cb);
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams6.addRule(10);
        mm2.setLayoutParams(layoutParams6);
        mm2.setBackground(com.bytedance.sdk.openadsdk.utils.FA.ZRu(context, "tt_video_black_desc_gradient"));
        mm2.setGravity(16);
        mm2.setVisibility(8);
        addView(mm2);
        com.bytedance.sdk.openadsdk.core.TFq.uR uRVar5 = new com.bytedance.sdk.openadsdk.core.TFq.uR(context);
        int i10 = com.bytedance.sdk.openadsdk.utils.sAl.jQo;
        uRVar5.setId(i10);
        RelativeLayout.LayoutParams layoutParams7 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams7.addRule(15);
        int iMZ5 = Cox.mZ(context, 12.0f);
        layoutParams7.leftMargin = iMZ5;
        layoutParams7.setMarginStart(iMZ5);
        uRVar5.setLayoutParams(layoutParams7);
        uRVar5.setScaleType(scaleType);
        uRVar5.setImageDrawable(com.bytedance.sdk.openadsdk.utils.FA.ZRu(context, "tt_leftbackbutton_titlebar_photo_preview"));
        mm2.addView(uRVar5);
        com.bytedance.sdk.openadsdk.core.TFq.FA fa4 = new com.bytedance.sdk.openadsdk.core.TFq.FA(context);
        fa4.setId(com.bytedance.sdk.openadsdk.utils.sAl.JVq);
        RelativeLayout.LayoutParams layoutParams8 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams8.addRule(15);
        int iMZ6 = Cox.mZ(context, 16.0f);
        layoutParams8.leftMargin = iMZ6;
        layoutParams8.rightMargin = iMZ;
        layoutParams8.setMarginStart(iMZ6);
        layoutParams8.setMarginEnd(iMZ);
        layoutParams8.addRule(17, i10);
        int i11 = com.bytedance.sdk.openadsdk.utils.sAl.LrZ;
        layoutParams8.addRule(0, i11);
        layoutParams8.addRule(1, i10);
        layoutParams8.addRule(16, i11);
        fa4.setLayoutParams(layoutParams8);
        fa4.setEllipsize(truncateAt);
        fa4.setGravity(16);
        fa4.setMaxLines(1);
        fa4.setSingleLine(true);
        fa4.setTextColor(-1);
        fa4.setTextSize(2, 17.0f);
        mm2.addView(fa4);
        com.bytedance.sdk.openadsdk.core.TFq.TFq tFq2 = new com.bytedance.sdk.openadsdk.core.TFq.TFq(context);
        tFq2.setId(i11);
        RelativeLayout.LayoutParams layoutParams9 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams9.addRule(21);
        layoutParams9.addRule(11);
        int iMZ7 = Cox.mZ(context, 14.0f);
        layoutParams9.rightMargin = iMZ7;
        layoutParams9.setMarginEnd(iMZ7);
        tFq2.setLayoutParams(layoutParams9);
        tFq2.setGravity(16);
        tFq2.setOrientation(1);
        mm2.addView(tFq2);
        com.bytedance.sdk.openadsdk.core.TFq.FA fa5 = new com.bytedance.sdk.openadsdk.core.TFq.FA(context);
        fa5.setId(com.bytedance.sdk.openadsdk.utils.sAl.hl);
        LinearLayout.LayoutParams layoutParams10 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams10.gravity = 1;
        fa5.setLayoutParams(layoutParams10);
        fa5.setGravity(16);
        fa5.setMaxLines(1);
        fa5.setSingleLine(true);
        fa5.setTextColor(-1);
        fa5.setTextSize(2, 12.0f);
        tFq2.addView(fa5);
        com.bytedance.sdk.openadsdk.core.TFq.TFq tFq3 = new com.bytedance.sdk.openadsdk.core.TFq.TFq(context);
        tFq3.setId(com.bytedance.sdk.openadsdk.utils.sAl.LO);
        RelativeLayout.LayoutParams layoutParams11 = new RelativeLayout.LayoutParams(-2, Cox.mZ(context, 40.0f));
        layoutParams11.addRule(12);
        layoutParams11.addRule(21);
        layoutParams11.addRule(11);
        tFq3.setLayoutParams(layoutParams11);
        tFq3.setGravity(16);
        tFq3.setOrientation(0);
        tFq3.setVisibility(8);
        addView(tFq3);
        com.bytedance.sdk.openadsdk.core.TFq.FA fa6 = new com.bytedance.sdk.openadsdk.core.TFq.FA(context);
        fa6.setId(com.bytedance.sdk.openadsdk.utils.sAl.klw);
        LinearLayout.LayoutParams layoutParams12 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams12.leftMargin = iMZ6;
        layoutParams12.rightMargin = iMZ5;
        layoutParams12.setMarginEnd(iMZ5);
        layoutParams12.setMarginStart(iMZ6);
        fa6.setLayoutParams(layoutParams12);
        fa6.setText(om.ZRu(context, "tt_00_00"));
        fa6.setTextColor(-1);
        fa6.setTextSize(2, 10.0f);
        tFq3.addView(fa6);
        SeekBar seekBar = new SeekBar(context);
        seekBar.setId(com.bytedance.sdk.openadsdk.utils.sAl.dkT);
        LinearLayout.LayoutParams layoutParams13 = new LinearLayout.LayoutParams(0, Cox.mZ(context, 5.0f));
        layoutParams13.gravity = 16;
        seekBar.setLayoutParams(layoutParams13);
        seekBar.setMax(100);
        seekBar.setPadding(0, 0, 0, 0);
        seekBar.setProgressDrawable(com.bytedance.sdk.openadsdk.utils.FA.ZRu(context, "tt_seek_progress"));
        seekBar.setThumb(com.bytedance.sdk.openadsdk.utils.FA.ZRu(context, "tt_seek_thumb"));
        seekBar.setThumbOffset(0);
        tFq3.addView(seekBar);
        com.bytedance.sdk.openadsdk.core.TFq.FA fa7 = new com.bytedance.sdk.openadsdk.core.TFq.FA(context);
        fa7.setId(com.bytedance.sdk.openadsdk.utils.sAl.gx);
        LinearLayout.LayoutParams layoutParams14 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams14.leftMargin = iMZ5;
        layoutParams14.rightMargin = iMZ6;
        layoutParams14.setMarginEnd(iMZ6);
        layoutParams14.setMarginStart(iMZ5);
        fa7.setLayoutParams(layoutParams14);
        fa7.setText(om.ZRu(context, "tt_00_00"));
        fa7.setTextColor(-1);
        fa7.setTextSize(2, 10.0f);
        tFq3.addView(fa7);
        com.bytedance.sdk.openadsdk.core.TFq.uR uRVar6 = new com.bytedance.sdk.openadsdk.core.TFq.uR(context);
        uRVar6.setId(com.bytedance.sdk.openadsdk.utils.sAl.Uf);
        uRVar6.setLayoutParams(new LinearLayout.LayoutParams(-2, -1));
        uRVar6.setPadding(iMZ6, 0, iMZ6, 0);
        uRVar6.setScaleType(scaleType);
        uRVar6.setVisibility(8);
        uRVar6.setImageDrawable(om.mZ(context, "tt_enlarge_video"));
        tFq3.addView(uRVar6);
        View lpVar = new lp(context);
        lpVar.setId(com.bytedance.sdk.openadsdk.utils.sAl.Ds);
        lpVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        addView(lpVar);
        com.bytedance.sdk.openadsdk.core.TFq.FA fa8 = new com.bytedance.sdk.openadsdk.core.TFq.FA(context);
        fa8.setId(com.bytedance.sdk.openadsdk.utils.sAl.qg);
        RelativeLayout.LayoutParams layoutParams15 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams15.leftMargin = iMZ5;
        layoutParams15.addRule(9);
        layoutParams15.addRule(20);
        fa8.setLayoutParams(layoutParams15);
        fa8.setBackgroundColor(Color.parseColor("#00000000"));
        fa8.setText(CampaignEx.JSON_NATIVE_VIDEO_CLOSE);
        fa8.setMinHeight(Cox.mZ(context, 44.0f));
        fa8.setCompoundDrawablesWithIntrinsicBounds(com.bytedance.sdk.openadsdk.utils.FA.ZRu(context, "tt_shadow_btn_back"), (Drawable) null, (Drawable) null, (Drawable) null);
        addView(fa8);
    }

    public sAl(Context context, AttributeSet attributeSet) {
        this(context, attributeSet, 0);
    }

    public sAl(Context context, AttributeSet attributeSet, int i10) {
        super(context, attributeSet, i10);
        ZRu(context);
    }
}
